### ISSUE TITLE
docker运行后无反应。。

### ISSUE THREAD

**Issue by Alexadnar** [valkjsaaa/auto-bilibili-recorder#10]
dockers运行命令如下：

`docker run -d --restart=always --name auto-bilibili-recorder -v /root/Record:/storage valkjsaaa/auto-bilibili-recorder:3.12`

yaml文件如下：

```
accounts:
  test_bot1:
    name:咦我的头发呢                                # 录播账号的名字，可以用于模版
    username: ""                         # 账号，可以是手机号
    password: ""                         # 密码
  test_bot2:
    name:七咔拉CHikalar                                # 录播账号的名字，可以用于模版
    username: ""                         # 账号，可以是手机号
    password: ""                         # 密码

rooms:
  - id: 14343955                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot1                              # 上传所应使用的账号
    tags: "录播,直播录屏,头发,咦我的头发呢"          # 上传视频所使用的 tag
    channel_id: 21                                 # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title            # 视频标题，可以使用模版
    source: "https://live.bilibili.com/14343955"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                                # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
  - id: 21706862                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot2                           # 上传所应使用的账号
    tags: "录播,直播录屏,头发,咦我的头发呢"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/21706862"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
```

请大佬指点。。
