### ISSUE TITLE
Ubuntu 20.04 无GPU版本无限重启

### ISSUE THREAD

**Issue by notplus** [valkjsaaa/auto-bilibili-recorder#3]
系统环境 Ubuntu 20.04 x86_64 无GPU版本，启动后无限重启。请问是否为登录接口问题？
log如下：
```
[2021-05-16 17:32:54][17721053530] 服务繁忙, 尝试使用V3接口登录
[2021-05-16 17:32:54][17721053530] 登录成功
login successfully! bot [removed login info]
Traceback (most recent call last):
  File "/webhook/process_video.py", line 7, in <module>
    record_upload_manager = RecordUploadManager("./recorder_config.yaml", "recorder_save.yaml")
  File "/webhook/record_upload_manager.py", line 32, in __init__
    self.config = RecorderConfig(yaml.load(file, Loader=yaml.FullLoader))
  File "/webhook/recorder_config.py", line 53, in __init__
    assert room.uploader in self.accounts
AssertionError
```

**Comment by valkjsaaa** [comment]
应该登录成功了，注意别贴 login 后面的那几个字符串，别人用了可以用来登陆你的账户。

assertion error 应该是你的 config 有问题，你把用户名密码去掉发下你的 config file 吧？

**Comment by notplus** [comment]
好的，感谢，这是我的config file，麻烦了。
```
accounts:
  test_bot:
    name: bot                             # 录播账号的名字，可以用于模版
    username: ""                         # 账号，可以是手机号
    password: ""                         # 密码
rooms:
  - id: 64458                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: bot                           # 上传所应使用的账号
    tags: "录播,直播录屏,DarkCarrot,星际争霸"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/64458"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      录播测试
```

**Comment by valkjsaaa** [comment]
应该这样就对了：
```
accounts:
  test_bot:
    name: bot                             # 录播账号的名字，可以用于模版
    username: ""                         # 账号，可以是手机号
    password: ""                         # 密码
rooms:
  - id: 64458                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot                           # 上传所应使用的账号
    tags: "录播,直播录屏,DarkCarrot,星际争霸"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/64458"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      录播测试
```
