### ISSUE TITLE
无法进行上传

### ISSUE THREAD

**Issue by waitsaber** [valkjsaaa/auto-bilibili-recorder#5]
运行环境：腾讯云广州区 centos7.6，Docker version 20.10.7, build f0df350，运行无显卡镜像。
能正常进行录播 ass转换 合并成mp4  合并完mp4后并没有进行上传的动作。
![图片](https://user-images.githubusercontent.com/67093172/121767903-d936b300-cb8d-11eb-9eb2-e52abdece1e9.png)
![图片](https://user-images.githubusercontent.com/67093172/121767941-0b481500-cb8e-11eb-9aed-4ff3253b6726.png)

**Comment by valkjsaaa** [comment]
发一下你的 recorder-config.yaml? 是不是配置不对啊，记得删掉你的用户名密码哈。

**Comment by waitsaber** [comment]
`accounts:
  test_bot:
    name: 安雪璃                             # 录播账号的名字，可以用于模版
    username: ""                         # 账号，可以是手机号
    password: ""                         # 密码
rooms:
  - id: 609304                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot                           # 上传所应使用的账号
    tags: "录播,自动录播,安雪璃"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/609304"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
      录播源文件 https://tsxk.jya.ng/$flv_path
  - id: 609304  # don't upload this room          # 不需要上传的直播间 ID，只需要填写 ID，会生成高能录播，但不会上传
rooms:
  - id: 3279447
    uploader: test_bot                           # 上传所应使用的账号
    tags: "录播,自动录播"                        # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/3279447"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
      录播源文件 https://tsxk.jya.ng/$flv_path
  - id: 3279447  # don't upload this room          # 不需要上传的直播间 ID，只需要填写 ID，会生成高能录播，但不会上传
 `
配置内容如上，上传这一项采用的是默认的设置，没有改动。

**Comment by valkjsaaa** [comment]
Rooms 部分应该这么写，只有只需要生成视频而不需要上传的直播间才这么写 `- id: 609304`，如果要上传就得写包括uploader在内的各种参数。你同时写了两种，程序默认用了后面写的那种，所以没有上传。

另外，注意你的缩进，yaml 是缩进敏感的。
```
rooms:
  - id: 609304                                   # 需要上传的直播间 ID，请填写完整号码，而不是短号，否则可能不会上传
    uploader: test_bot                           # 上传所应使用的账号
    tags: "录播,自动录播,安雪璃"              # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/609304"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
      录播源文件 https://tsxk.jya.ng/$flv_path
  - id: 3279447
    uploader: test_bot                           # 上传所应使用的账号
    tags: "录播,自动录播"                        # 上传视频所使用的 tag
    channel_id: 21                               # 上传视频所用的分区 ID，参考：https://github.com/greats3an/bilibili-toolman#分区表
    title: 【$name】$yy年$mm月$dd日 $title         # 视频标题，可以使用模版
    source: "https://live.bilibili.com/3279447"      # 转载来源，建议填写直播间短号（如果有的话）链接
    description: >-                              # 视频描述，可以使用模版
      由 $uploader_name 录播脚本上传
      录播源文件 https://tsxk.jya.ng/$flv_path
```
