### ISSUE TITLE
能否添加多种登录方式

### ISSUE THREAD

**Issue by orangeWindis** [valkjsaaa/auto-bilibili-recorder#6]
能不能添加手机验证码/cookie登录

**Comment by orangeWindis** [comment]
添加对代理池的支持也可以，因为我国外的VPS被检测环境风险导致无法登陆

**Comment by valkjsaaa** [comment]
手机验证码有点麻烦，我没看到相关的 API，有的话发个链接？
代理池可能是可行的，可以实现成这个样子：
```
login_proxy: "https://123.45.67.89:1234"
accounts:
  test_bot:
    name: 测试录播bot                             # 录播账号的名字，可以用于模版
    username: "username"                         # 账号，可以是手机号
    password: "PaSsWoRd"                         # 密码
```

然后 [`recorder_config.py`](https://github.com/valkjsaaa/auto-bilibili-recorder/blob/master/recorder_config.py) 改一下就可以吧。其中登陆之前可以用这个办法加代理 `b.set_proxy(add=proxy_url)`。

我一时半会儿没时间，你可以试着改改，交个 pull request。
